Verify the example `.scala-steward.conf`
This checks that the example `.scala-steward.conf` in the docs is equivalent
to the JSON one gets when parsing, decoding and encoding that example.

With this change, the `docs/mdoc` task fails currently with:
```diff
error: repo-specific-configuration.md:211:1: Diff between parsed input (-) and encoded object (+):
         "groupId" : "com.example",
-        "version" : "2."
+        "version" : {
+          "prefix" : "2."
+        }
       },
       "pullRequests" : {
-        "frequency" : "30 day"
+        "frequency" : "30 days"
       }
       "pullRequests" : {
-        "frequency" : "14 day"
+        "frequency" : "14 days"
       }
   "signoffCommits" : true,
-  "updatePullRequests" : "always | on-conflicts | never",
+  "updatePullRequests" : "on-conflicts",
   "updates" : {
         "groupId" : "org.acme",
-        "version" : "1.0"
+        "version" : {
+          "prefix" : "1.0"
+        }
       }
         "groupId" : "com.example",
-        "version" : "1.1."
+        "version" : {
+          "prefix" : "1.1."
+        }
       }
```
In subsequent commits I'll will fix these reported differences.

Closes: #1341