Add `-tasty-reader` to `doc/scalacOptions`
Adding Scala 3 to `doc/crossScalaVersions` results in the following
error
```
sbt:scala-steward> doc/mdoc
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("."), "docs"):
[error]    org.scala-lang.modules:scala-collection-compat _3, _2.13
[error]    com.github.plokhotnyuk.jsoniter-scala:jsoniter-scala-core _3, _2.13
```
which I believe is due to using `for3Use2_13` for Coursier. I therefore
kept the `doc` project Scala 2-only and added the `-tasty-reader`
scalac option to prevent this error
```
sbt:scala-steward> doc/mdoc
[info] running mdoc.SbtMain
error: error while loading Cli, Missing dependency 'Add -Ytasty-reader to scalac options to parse the TASTy in modules/core/.jvm/target/scala-3.3.4/classes/org/scalasteward/core/application/Cli.tasty', required by modules/core/.jvm/target/scala-3.3.4/classes/org/scalasteward/core/application/Cli.tasty
[error] java.lang.RuntimeException: mdoc failed
```