Import `MockEffOps` to fix compile errors with Scala 3
This is in preparation for compiling with Scala 3 and fixes errors like
this:
```
 -- [E008] Not Found Error: modules/core/src/test/scala/org/scalasteward/core/BuiltinConfigFilesTest.scala:38:9
 36 |      val migrations = artifactMigrationsLoader
 37 |        .loadAll(ArtifactCfg(List(), disableDefaults = false))
 38 |        .runA(initialState)
    |                       ^
    |value runA is not a member of org.scalasteward.core.mock.MockEff[
    |  List[org.scalasteward.core.update.artifact.ArtifactChange]], but could be made available as an extension method.
    |
    |The following import might fix the problem:
    |
    |  import org.scalasteward.core.mock.MockEffOps
```

I think the change in the Scala 3 compiler that makes this import
necessary, is ["3. Package prefixes no longer contribute to the implicit search scope of a type"](https://docs.scala-lang.org/scala3/reference/changed-features/implicit-resolution.html).