Update GitLab example (#2943)
* Update GitLab example

Unfortunately, the current example does not work out of the box. 

### 1) Not enough permissions without `chmod +x "$CI_PROJECT_DIR/askpass.sh"`

```
java.io.IOException: Cannot run program "/builds/xxx/scala-steward/askpass.sh" (in directory "/builds/xxx/scala-steward/workspace"): error=13, Permission denied
```

### 2) Without trailing `\` the script line is not formatted correctly

```
/opt/docker/bin/scala-steward  # collapsed multi-line command
Missing expected flag --forge-login, or command (validate-repo-config)!
Usage:
  ....
```