Ignore updates of sbt-pack
It fails with

failed finding updates for ArtificialProject(ScalaVersion(2.12.8),SbtVersion(1.2.8),List(),List(Dependency(org.xerial.sbt,sbt-pack,sbt-pack,0.9.1,Some(SbtVersion(1.0)),None)))
java.io.IOException: [info] Loading settings for project global-plugins from sbt-updates.sbt ...
[info] Loading global plugins from /home/frank/.sbt/1.0/plugins
[info] Loading settings for project updates-build from plugins.sbt ...
[info] Loading project definition from /home/frank/code/scala-steward/workspace/updates/project
[info] Updating ProjectRef(uri("file:/home/frank/code/scala-steward/workspace/updates/project/"), "updates-build")...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[error] java.lang.ExceptionInInitializerError
[error]         at xerial.sbt.pack.PackPlugin$.packSettings$lzycompute(PackPlugin.scala:114)
...
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: A named attribute key must start with a lowercase letter: List of excluding files from the archive