Fix `deleteRemoteBranch` call
Changes `git push origin --delete origin/update` to
`git push origin --delete update` because it fails with the
remote prefix:
```
git push origin --delete origin/update' exited with code 1
error: unable to delete 'origin/update': remote ref does not exist
```