Ignore com.iheart:sbt-play-swagger in update check
It fails with
```
[error] java.lang.NoClassDefFoundError: com/typesafe/sbt/packager/archetypes/JavaAppPackaging$
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.requires(SwaggerPlugin.scala:16)
[error]         at sbt.Plugins$.asRequirements(Plugins.scala:353)
```