Harmonize imports for http4s and circe literals
This is in preparation for compiling with Scala 3 and prevents errors
like
```
 -- [E008] Not Found Error: modules/core/src/test/scala/org/scalasteward/core/coursier/DependencyMetadataTest.scala:7:28
 7 |import org.http4s.implicits.http4sLiteralsSyntax
   |                            ^^^^^^^^^^^^^^^^^^^^
   | value http4sLiteralsSyntax is not a member of object org.http4s.implicits
```
and
```

 -- [E008] Not Found Error: modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubAuthAlgTest.scala:4:24
 4 |import io.circe.literal.JsonStringContext
   |                        ^^^^^^^^^^^^^^^^^
   |               value JsonStringContext is not a member of io.circe.literal
```
It also prefers importing `org.http4s.syntax.literals._` over
`org.http4s.implicits._` so that we import less and are more explicit
about what the import is about.